# Generated by Django 5.0.1 on 2024-01-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('c_pass', models.CharField(max_length=20)),
                ('agree', models.BooleanField()),
            ],
        ),
    ]
